# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dd2440a7e81d27d1d695066e1be8e2140cfc30ccfde0f8ab5b55b88cde47e627bf4a5b177eb6fa2ec482d5ba6279ea09e51bbc42512e6298f2216e83109536b

test:
  secret_key_base: 8f523a6f21c273eedee6b255601b55ed9d108062a293ecd46bf1653b2ec82b5d8f12701b909d3acf4772e728ccdb52fa152b73cbbb60727d2d8edce14837e01c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
